### ISSUE TITLE
test cases failed with python 3.6.6

### ISSUE THREAD

**Issue by chengguangnan** [coleifer/beefish#6]
It produces different results every time I run it with the same input and key. 

Also I can't decrypt the file on another machine. 

Also I found the test has failed.

```
test_chunk_sizes (__main__.TestEncryptDecrypt) ... ERROR
test_encrypt_decrypt (__main__.TestEncryptDecrypt) ... ERROR
test_key (__main__.TestEncryptDecrypt) ... ERROR
test_stringio (__main__.TestEncryptDecrypt) ... ERROR
test_chunk_sizes (__main__.TestEncryptDecryptAES) ... ok
test_encrypt_decrypt (__main__.TestEncryptDecryptAES) ... ok
test_key (__main__.TestEncryptDecryptAES) ... ok
test_stringio (__main__.TestEncryptDecryptAES) ... ok

======================================================================
ERROR: test_chunk_sizes (__main__.TestEncryptDecrypt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 191, in test_chunk_sizes
    buf, decrypted = self.crypt_data(num_bytes, b'a', chunk_size=i)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 163, in crypt_data
    self.cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 122, in encrypt_file
    encrypt(in_fh, out_fh, key, chunk_size, cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 76, in encrypt
    cipher = get_cipher(key, iv)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 48, in get_blowfish_cipher
    return Blowfish.new(key, Blowfish.MODE_CBC, iv)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 234, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

======================================================================
ERROR: test_encrypt_decrypt (__main__.TestEncryptDecrypt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 178, in test_encrypt_decrypt
    encrypt_flow(b'a')
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 175, in encrypt_flow
    buf, decrypted = self.crypt_data(i, ch)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 163, in crypt_data
    self.cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 122, in encrypt_file
    encrypt(in_fh, out_fh, key, chunk_size, cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 76, in encrypt
    cipher = get_cipher(key, iv)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 48, in get_blowfish_cipher
    return Blowfish.new(key, Blowfish.MODE_CBC, iv)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 234, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

======================================================================
ERROR: test_key (__main__.TestEncryptDecrypt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 184, in test_key
    buf, decrypted = self.crypt_data(128, b'a', self.key, self.key+'x')
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 163, in crypt_data
    self.cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 122, in encrypt_file
    encrypt(in_fh, out_fh, key, chunk_size, cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 76, in encrypt
    cipher = get_cipher(key, iv)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 48, in get_blowfish_cipher
    return Blowfish.new(key, Blowfish.MODE_CBC, iv)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 234, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

======================================================================
ERROR: test_stringio (__main__.TestEncryptDecrypt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 203, in test_stringio
    encrypt(in_buf, out_buf, self.key, i, self.cipher_type)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 76, in encrypt
    cipher = get_cipher(key, iv)
  File "/Users/chengguangnan/anaconda3/bin/beefish.py", line 48, in get_blowfish_cipher
    return Blowfish.new(key, Blowfish.MODE_CBC, iv)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 234, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/Users/chengguangnan/anaconda3/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 109, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

----------------------------------------------------------------------
Ran 8 tests in 0.262s

FAILED (errors=4)
```

**Comment by coleifer** [comment]
Not sure, it seems to work fine for me on Python 3.6.3. What version of beefish?

**Comment by coleifer** [comment]
Latest is 0.2.0

**Comment by coleifer** [comment]
Maybe your pycrypto is out-of-date, also? This seems illustrative of a similar problem:

https://stackoverflow.com/questions/50302827/object-type-class-str-cannot-be-passed-to-c-code-virtual-environment

**Comment by chengguangnan** [comment]
```
pycrypto                           2.6.1
beefish                            0.2.0
```

The issue was that beefish produces different output (credentials.yml.enc) every time with the same IV. Below is the code. Yesterday I have to use AES directly to work around this issue. 

```
from os import environ as env
from Crypto.Cipher import AES

__master_key = env.get("master_key")

if __master_key is None:
    assert False, "master_key is required"

obj = AES.new(__master_key.encode("utf-8"), AES.MODE_CFB, b'This is an IV456')

with open('credentials.yml') as input:
    message = input.read()
    ciphertext = obj.encrypt(message.encode("utf-8"))
    with open('credentials.yml.enc', 'wb') as output:
        output.write(ciphertext)
```

**Comment by coleifer** [comment]
Weird... On my machine (Python 3.6.5, PyCrypto 2.6.1 'final' and beefish 0.2.0) all the tests are passing.

I see from the [StackOverflow link](https://stackoverflow.com/questions/50302827/object-type-class-str-cannot-be-passed-to-c-code-virtual-environment) that someone else is running into a similar problem with Anaconda.

> The issue was that beefish produces different output (credentials.yml.enc) every time with the same IV. 

The IV is randomly chosen by beefish when encrypting a file (regardless of which cipher you use). The `generate_iv()` function returns a series of random bytes. So encrypting a file twice, even with the same passphrase, will return different output because the IV will presumably be different.

**Comment by coleifer** [comment]
I added a new test in 42ccee70e6dca579f24b2ce3f6ab85e7405ecfcd that shows that beefish produces the same ciphertext when given 1) same input, 2) same passphrase and 3) same IV. The tests are passing for both blowfish and aes modes.

I'm not sure what to do as I can't replicate your issue or the error you initially reported.

**Comment by chengguangnan** [comment]
Oh I see. The IV is written to the file. Sorry about this.
