### ISSUE TITLE
Object type <class 'str'> cannot be passed to C code

### ISSUE THREAD

**Issue by megahomyak** [coleifer/beefish#8]
```
>>> beefish.encrypt_file("input.png", "output.png" "p@ssword")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\beefish.py", line 127, in encrypt_file
    encrypt(in_fh, out_fh, key, chunk_size, cipher_type)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\beefish.py", line 81, in encrypt
    cipher = get_cipher(key, iv)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\beefish.py", line 53, in get_blowfish_cipher
    return Blowfish.new(key, Blowfish.MODE_CBC, iv)  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\Blowfish.py", line 146, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Cipher\Blowfish.py", line 77, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "C:\Users\megahomyak\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Crypto\Util\_raw_api.py", line 138, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code
```

My beefish version is 0.2.1

And every other encryption or decryption method have this problem

**Comment by coleifer** [comment]
I don't know, this must be some windows issue. Works fine on linux. You can try encoding your key, maybe? `'p@ssword'.encode('utf8')`
